### PR TITLE
Refactoring submit so that submit function is passed into the decorat…

### PR DESCRIPTION
**Pull request by aohx075**
…ed onSubmit prop

### CODE REVIEW

**Comment by jameslnewell** [comment]
Solves #10

**Comment by jameslnewell** [comment]
This PR requires a major version bump so I'm going to postpone releasing it until #9 is implemented (which will also require a major version bump). Was anyone in your team working on #9? They did mention in a demo the other day that the data "persisting" in the forms after the user navigates away was an issue they plan to fix.

**Comment by jameslnewell** [comment]
P.S. Can you remind me of the use case for this again. Ty.

**Comment by jameslnewell** [comment]
Just implemented #9. Can you please test master before I release it.

**Comment by aohx075** [comment]
It's not a blocker but the use case for it was to be able to pass attributes from the Redux State during a submit bit more elegantly. E.g. if you're submitting data that's collated over 2 forms. This will allow you to define your own submit method within the React component and grab data from the Redux State. This way we won't need to have a method inside the actions to do it and can submit all required data together from the same place.

**Comment by aohx075** [comment]
Just testing destroyOnUnmount but it seems to be keeping 'submitted' to true. Is that expected?

**Comment by jameslnewell** [comment]
Does your submit method return a promise? If that's resolving after the component has been unmounted the state will be created via the finish submit reducer.

**Comment by aohx075** [comment]
We've wired up our submit method so that after its request to the server succeeds then it updates the route before resolving. I think we can work around it by only disabling the submit button when 'submitting'. 

But in general if you're submitting the page and then having to navigate to the next page on submit wouldn't it always unmount the component before resolving? i.e. is there another way of routing to a different page after a successful submission that doesn't happen in the 'submit' method?

**Comment by jameslnewell** [comment]
Yeah you'll have to navigate after resolving the promise (and if its something the user cares about submitting you probably should be waiting for the promise to resolve so you can give the user feedback if it fails). 

If you don't want to make the user wait to confirm successful submission before navigating, you can manually wire up your forms to destroy on mount instead.

e.g. 
```javascript
componentDidMount() {
  this.props.destroy();
}
```

**Pull request merged**
